# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nirtitle', models.TextField()),
                ('planitem', models.CharField(blank=True, max_length=255, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('approvedate', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='authors.Author')),
                ('authorsother', models.ManyToManyField(to='authors.OtherAuthor')),
                ('leadersemployees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nir_leader', to='authors.Author', verbose_name='Научный руководитель')),
                ('leadersemployeessubdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nir_leadersubdivision', to='authors.Subdivision', verbose_name='Подразделение научного руководителя')),
                ('leadersnotemployees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nir_leadernotemployee', to='authors.OtherAuthor', verbose_name='Научный руководитель (не сотрудник)')),
            ],
            options={
                'verbose_name': 'Научно-исследовательская работа',
                'verbose_name_plural': 'Научно-исследовательские работы',
                'ordering': ('nirtitle',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Организация (сторонние авторы)',
                'verbose_name_plural': 'Организации (сторонние авторы)',
                'ordering': ('organization_name',),
            },
        ),
        migrations.CreateModel(
            name='ReasonNIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reasonname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Основание для проведения НИР',
                'verbose_name_plural': 'Основания для проведения НИР',
                'ordering': ('reasonname',),
            },
        ),
        migrations.CreateModel(
            name='Researchresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researchresultname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Результат исследования',
                'verbose_name_plural': 'Результаты исследования',
                'ordering': ('researchresultname',),
            },
        ),
        migrations.CreateModel(
            name='ReasonInNIR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nir.NIR')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nir.ReasonNIR')),
            ],
            options={
                'verbose_name': 'Основание проведения в НИР(ManyToMany)',
                'verbose_name_plural': 'Основания проведения в НИР(ManyToMany)',
            },
        ),
        migrations.AddField(
            model_name='nir',
            name='organization',
            field=models.ManyToManyField(to='nir.Organization', verbose_name='Организация(сторонние авторы)'),
        ),
        migrations.AddField(
            model_name='nir',
            name='reason',
            field=models.ManyToManyField(through='nir.ReasonInNIR', to='nir.ReasonNIR'),
        ),
        migrations.AddField(
            model_name='nir',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nir.Researchresults'),
        ),
        migrations.AddField(
            model_name='nir',
            name='subdivisions',
            field=models.ManyToManyField(to='authors.Subdivision'),
        ),
    ]
