# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Основание')),
            ],
            options={
                'verbose_name': 'Основание для проведения исследования',
                'verbose_name_plural': 'Основания для проведения исследования',
                'ordering': ('reason',),
            },
        ),
        migrations.CreateModel(
            name='Researchkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Вид исследования',
                'verbose_name_plural': 'Виды исследований',
                'ordering': ('kindename',),
            },
        ),
        migrations.CreateModel(
            name='Researchplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Место проведения исследования',
                'verbose_name_plural': 'Места проведения исследований',
                'ordering': ('place',),
            },
        ),
        migrations.CreateModel(
            name='Researchstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Статус исследователя',
                'verbose_name_plural': 'Статусы исследователей',
                'ordering': ('statusname',),
            },
        ),
        migrations.CreateModel(
            name='Dissertationresearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebegin', models.IntegerField(blank=True, null=True, verbose_name='Год начала')),
                ('dateend', models.IntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('dateprotect', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('dissertationtheme', models.TextField(verbose_name='Тема исследования')),
                ('result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат исследования')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='authors.Author', verbose_name='Автор исследования (сотрудник)')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.Researchkind', verbose_name='Вид исследования')),
                ('leadersemployees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadersemployee', to='authors.Author', verbose_name='Научный руководитель (сотрудник)')),
                ('leadersemployeessubdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadersemployeessubdivision', to='authors.Subdivision', verbose_name='Подразделение научного руководителя')),
                ('leadersnotemployees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leadersnotemployee', to='authors.OtherAuthor', verbose_name='Научный руководитель (не сотрудник)')),
                ('otherauthor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.OtherAuthor', verbose_name='Автор исследования (не сотрудник)')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.Reason', verbose_name='Основание для проведения исследования')),
                ('researchplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.Researchplace', verbose_name='Место проведения исследования')),
                ('researchplacesubdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdivisionplace', to='authors.Subdivision', verbose_name='Подразделение Академии МВД РБ (место проведения)')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dissertationresearch.Researchstatus', verbose_name='Статус исследователя')),
            ],
            options={
                'verbose_name': 'Диссертационное исследование',
                'verbose_name_plural': 'Диссертационные исследования',
                'ordering': ('id',),
            },
        ),
    ]
