# Generated by Django 2.2.7 on 2020-01-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_subdivisiontableemployee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubdivisionTableEmployee',
        ),
    ]
