# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=255, verbose_name='Патентообладатель')),
            ],
            options={
                'verbose_name': 'Патентообладатель',
                'verbose_name_plural': 'Патентообладатели',
                'ordering': ('ownername',),
            },
        ),
        migrations.CreateModel(
            name='PatentownerInPLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patentowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pld.PatentOwner')),
            ],
            options={
                'verbose_name': 'Патентообладатели в ПЛД',
                'verbose_name_plural': 'Патентообладатели в ПЛД',
            },
        ),
        migrations.CreateModel(
            name='PLDkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindtitle', models.CharField(max_length=255, verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'Вид патентно-лицензионной деятельности',
                'verbose_name_plural': 'Виды патентно-лицензионной деятельности',
                'ordering': ('kindtitle',),
            },
        ),
        migrations.CreateModel(
            name='PLD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pldtitle', models.CharField(max_length=255, verbose_name='Название ПЛД')),
                ('actionstart', models.DateField(blank=True, null=True, verbose_name='Начало действия')),
                ('registrationdate', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('requestdate', models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки')),
                ('panentnumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер панетна')),
                ('authors', models.ManyToManyField(to='authors.Author', verbose_name='Автор')),
                ('authorsother', models.ManyToManyField(to='authors.OtherAuthor', verbose_name='Сторонний автор')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pld.PLDkind', verbose_name='Вид ПЛД')),
                ('patentowner', models.ManyToManyField(through='pld.PatentownerInPLD', to='pld.PatentOwner', verbose_name='Патентообладатель')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Патентно-лицензионная деятельность',
                'verbose_name_plural': 'Патентно-лицензионные деятельности',
                'ordering': ('pldtitle',),
            },
        ),
        migrations.AddField(
            model_name='patentownerinpld',
            name='pld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pld.PLD'),
        ),
    ]
