# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dissertationresearch', '0001_initial'),
        ('authors', '0001_initial'),
        ('sciencework', '0001_initial'),
        ('nir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developmentkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindtitle', models.CharField(max_length=255, verbose_name='Вид внедренной разработки')),
            ],
            options={
                'verbose_name': 'Вид внедренной разработки',
                'verbose_name_plural': 'Виды внедренной разработки',
                'ordering': ('kindtitle',),
            },
        ),
        migrations.CreateModel(
            name='Introductionkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductionkindtitle', models.CharField(max_length=255, verbose_name='Вид внедрения')),
            ],
            options={
                'verbose_name': 'Вид внедрения',
                'verbose_name_plural': 'Виды внедрения',
                'ordering': ('introductionkindtitle',),
            },
        ),
        migrations.CreateModel(
            name='Introductionorganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(max_length=255, verbose_name='Организация внедрения')),
            ],
            options={
                'verbose_name': 'Организация внедрения',
                'verbose_name_plural': 'Организации внедрения',
                'ordering': ('organizationname',),
            },
        ),
        migrations.CreateModel(
            name='ANR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvedate', models.DateField(verbose_name='Дата внедрения')),
                ('halfyear', models.CharField(blank=True, max_length=1, null=True, verbose_name='Полугодие внедрения')),
                ('authorsother', models.TextField(blank=True, null=True, verbose_name='Сторонние авторы')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('is_student_participation', models.BooleanField(blank=True, null=True, verbose_name='Участие обучающихся')),
                ('student', models.TextField(blank=True, null=True, verbose_name='Обучающйися')),
                ('development_has_not_base', models.BooleanField(blank=True, null=True, verbose_name='Разработка, отсутствует в базе(boolean)')),
                ('development_without_base', models.TextField(blank=True, null=True, verbose_name='Разработка, отсутствующая в базе')),
                ('adjunct', models.TextField(blank=True, null=True, verbose_name='Адъюнкт')),
                ('authors', models.ManyToManyField(blank=True, to='authors.Author', verbose_name='Авторы-сотрудники Академии')),
                ('developmentkind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anr.Developmentkind', verbose_name='Вид внедренной разработки')),
                ('dissertation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertationresearch.Dissertationresearch', verbose_name='Диссертационное исследование')),
                ('introductionkind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anr.Introductionkind', verbose_name='Вид внедрения')),
                ('introductionorganization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anr.Introductionorganization', verbose_name='Организация внедрения')),
                ('nir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nir.NIR', verbose_name='Научно-исследовательская работа')),
                ('sciencework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sciencework.Publication', verbose_name='Публикация')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision', verbose_name='Подразделения разработки')),
            ],
            options={
                'verbose_name': 'Апробация научных результатов',
                'verbose_name_plural': 'Апробации научных результатов',
                'ordering': ('developmentkind',),
            },
        ),
    ]
