# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('sciencework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitytitle', models.CharField(max_length=255, verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
                'ordering': ('activitytitle',),
            },
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('сounciltitle', models.CharField(max_length=255, verbose_name='Название совета')),
            ],
            options={
                'verbose_name': 'Вид совета',
                'verbose_name_plural': 'Виды совета',
                'ordering': ('сounciltitle',),
            },
        ),
        migrations.CreateModel(
            name='CouncilCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Категория совета')),
            ],
            options={
                'verbose_name': 'Категория совета',
                'verbose_name_plural': 'Категории советов',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Dissertation_kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_title', models.CharField(max_length=255, verbose_name='Вид диссертации')),
            ],
            options={
                'verbose_name': 'Вид диссертации',
                'verbose_name_plural': 'Виды диссертаций',
                'ordering': ('kind_title',),
            },
        ),
        migrations.CreateModel(
            name='Edition_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=255, verbose_name='Наименование научного издания')),
            ],
            options={
                'verbose_name': 'Наименование научного издания',
                'verbose_name_plural': 'Наименования научных изданий',
                'ordering': ('edition_name',),
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutionname', models.CharField(max_length=255, verbose_name='Название учреждения')),
            ],
            options={
                'verbose_name': 'Учреждение, при котором действует совет',
                'verbose_name_plural': 'Учреждения, при которых действует совет',
                'ordering': ('institutionname',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worktitle', models.CharField(max_length=255, verbose_name='Название работы')),
            ],
            options={
                'verbose_name': 'Работа, выполненная в составе совета',
                'verbose_name_plural': 'Работы, выполненные в составе совета',
                'ordering': ('worktitle',),
            },
        ),
        migrations.CreateModel(
            name='Otherkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defense_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место защиты')),
                ('research_theme', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема исследования')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='Дата защиты')),
                ('work_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Основание проведения работ')),
                ('work_kind', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вид работы')),
                ('work_subcontractors', models.CharField(blank=True, max_length=255, null=True, verbose_name='Соисполнители')),
                ('study_name', models.TextField(blank=True, null=True, verbose_name='Наименование исследования, основание включения в состав рабочей группы')),
                ('group_establishment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение, в котором создана рабочая группа(ВНК)')),
                ('participation_result', models.CharField(blank=True, max_length=255, null=True, verbose_name='Результат участия')),
                ('research_institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Учреждение (организация), представившее исследование')),
                ('other_year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.ActivityKind', verbose_name='Вид деятельности')),
                ('aspirant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.OtherAuthor', verbose_name='Соискатель')),
                ('authors', models.ManyToManyField(to='authors.Author', verbose_name='Члены совета')),
                ('completed_work_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='council_work', to='otherkind.Work', verbose_name='Работа, выполненная в составе совета')),
                ('completed_work_editoral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editoral_work', to='otherkind.Work', verbose_name='Работа, выполненная в составе редколлегии')),
                ('dissertation_kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.Dissertation_kind', verbose_name='Вид диссертации')),
                ('edition_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.Edition_name', verbose_name='Наименование научного издания')),
                ('founder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Organizatorforum', verbose_name='Учредитель научного издания')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.Institution', verbose_name='Учреждение, при котором действует совет')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision')),
                ('сouncil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.Council', verbose_name='Совет')),
            ],
            options={
                'verbose_name': 'Иной вид деятельности',
                'verbose_name_plural': 'Иные виды деятельности',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='council',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otherkind.CouncilCategory', verbose_name='Категория'),
        ),
    ]
