# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsInPublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('isauthor', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.Author')),
            ],
            options={
                'verbose_name': 'Авторы публикации',
                'verbose_name_plural': 'Авторы публикаций',
            },
        ),
        migrations.CreateModel(
            name='Cityforforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityforumtitle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Страна проведения форума',
                'verbose_name_plural': 'Страны проведения форума',
                'ordering': ('cityforumtitle',),
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conferencename', models.TextField(verbose_name='Название конференции')),
                ('forumdate', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('forumcountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Cityforforum', verbose_name='Страна проведения')),
            ],
            options={
                'verbose_name': 'Конференция',
                'verbose_name_plural': 'Конференции',
                'ordering': ('conferencename',),
            },
        ),
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digestname', models.CharField(max_length=255)),
                ('invak', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Сборник статей',
                'verbose_name_plural': 'Сборники статей',
                'ordering': ('digestname',),
            },
        ),
        migrations.CreateModel(
            name='Grif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grifname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Гриф',
                'verbose_name_plural': 'Грифы',
                'ordering': ('grifname',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'В чьих интересах',
                'verbose_name_plural': 'В чьих интересах',
                'ordering': ('interestname',),
            },
        ),
        migrations.CreateModel(
            name='InternationalBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Международная база научного тестирования',
                'verbose_name_plural': 'Международные базы научного тестирования',
                'ordering': ('basename',),
            },
        ),
        migrations.CreateModel(
            name='Kindkonf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Вид научного форума',
                'verbose_name_plural': 'Виды научных форумов',
                'ordering': ('kindname',),
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazinename', models.CharField(max_length=255)),
                ('invak', models.BooleanField(blank=True, null=True)),
                ('ininternational', models.ManyToManyField(blank=True, to='sciencework.InternationalBase', verbose_name='Международная база научного цитирования')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журналы',
                'ordering': ('magazinename',),
            },
        ),
        migrations.CreateModel(
            name='Organizatorforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организатор форума',
                'verbose_name_plural': 'Организаторы форумов',
                'ordering': ('orgname',),
            },
        ),
        migrations.CreateModel(
            name='Orgfounder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Организация учредитель сборника',
                'verbose_name_plural': 'Организации учредители сборников',
                'ordering': ('orgname',),
            },
        ),
        migrations.CreateModel(
            name='Publicationkind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('publicationkind', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Вид публикации',
                'verbose_name_plural': 'Виды публикации',
                'ordering': ('publicationkind',),
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishername', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
                'ordering': ('publishername',),
            },
        ),
        migrations.CreateModel(
            name='Statuskonf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusname', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Статус начного форума',
                'verbose_name_plural': 'Статусы научных форумов',
                'ordering': ('statusname',),
            },
        ),
        migrations.CreateModel(
            name='Subspecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Подвид учебного издания',
                'verbose_name_plural': 'Подвиды учебных изданий',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('halfyear', models.CharField(default='Не указано', max_length=100)),
                ('outputdata', models.TextField(blank=True, null=True)),
                ('sheetcount', models.CharField(blank=True, max_length=100, null=True)),
                ('invak', models.BooleanField(blank=True, null=True)),
                ('workisforeignauthors', models.BooleanField(blank=True, null=True)),
                ('authorcount', models.IntegerField(blank=True, default=0, null=True)),
                ('scienceworkstudentparticipation', models.BooleanField(blank=True, default=False, null=True)),
                ('forumdate', models.DateField(blank=True, null=True)),
                ('authors', models.ManyToManyField(through='sciencework.AuthorsInPublication', to='authors.Author')),
                ('conference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Conference')),
                ('digest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Digest')),
                ('forumcountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Cityforforum')),
                ('forumstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Statuskonf')),
                ('grif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Grif')),
                ('ininternationals', models.ManyToManyField(to='sciencework.InternationalBase')),
                ('interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Interest')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Publicationkind')),
                ('kindforum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Kindkonf')),
                ('magazine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Magazine')),
                ('organizatorforum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Organizatorforum')),
                ('orgfounders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Orgfounder')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Publisher')),
                ('subdivisions', models.ManyToManyField(to='authors.Subdivision')),
                ('subspecies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Subspecies')),
            ],
            options={
                'verbose_name': 'Публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ('kind',),
            },
        ),
        migrations.AddField(
            model_name='digest',
            name='ininternational',
            field=models.ManyToManyField(blank=True, to='sciencework.InternationalBase', verbose_name='Международная база научного цитирования'),
        ),
        migrations.AddField(
            model_name='conference',
            name='forumstatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Statuskonf', verbose_name='Статус научного форума'),
        ),
        migrations.AddField(
            model_name='conference',
            name='kindforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Kindkonf', verbose_name='Вид научного форума'),
        ),
        migrations.AddField(
            model_name='conference',
            name='moderators',
            field=models.ManyToManyField(blank=True, to='authors.Author', verbose_name='Модераторы научного форума/руководители секции'),
        ),
        migrations.AddField(
            model_name='conference',
            name='organizatorforum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sciencework.Organizatorforum', verbose_name='Организатор научного форума'),
        ),
        migrations.AddField(
            model_name='authorsinpublication',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sciencework.Publication'),
        ),
    ]
