# Generated by Django 2.2.7 on 2019-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciencework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conferencename_short',
            field=models.TextField(blank=True, null=True, verbose_name='Название конференции(сокращенное)'),
        ),
    ]
