# Generated by Django 2.2.7 on 2020-03-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_count', models.IntegerField(blank=True, null=True, verbose_name='Количество посещений')),
            ],
            options={
                'verbose_name': 'Количество посещений',
                'verbose_name_plural': 'Количества посещений',
                'ordering': ('id',),
            },
        ),
    ]
