# Generated by Django 2.2.7 on 2021-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forAMIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcounter',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='Количество посещений'),
        ),
    ]
