# Generated by Django 2.2.7 on 2019-12-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicdegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ученая степень')),
            ],
            options={
                'verbose_name': 'Ученая степень',
                'verbose_name_plural': 'Ученые степени',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Academicrank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Ученое звание')),
            ],
            options={
                'verbose_name': 'Ученое звание',
                'verbose_name_plural': 'Ученые звания',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Candidatespecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidatespecialtytitle', models.CharField(max_length=255, verbose_name='Название кандидатской диссертации')),
            ],
            options={
                'verbose_name': 'Кандидатская специальность',
                'verbose_name_plural': 'Кандидатские специальности',
                'ordering': ('candidatespecialtytitle',),
            },
        ),
        migrations.CreateModel(
            name='Doctorspecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorspecialtytitle', models.CharField(max_length=255, verbose_name='Название докторской диссертации')),
            ],
            options={
                'verbose_name': 'Докторская специальность',
                'verbose_name_plural': 'Докторские специальности',
                'ordering': ('doctorspecialtytitle',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('positionname', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('positionname',),
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('rank', models.CharField(max_length=100, verbose_name='Звание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivisiongroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivisiongroupname', models.CharField(max_length=255, verbose_name='Группа подразделений')),
            ],
            options={
                'verbose_name': 'Группа подразделений',
                'verbose_name_plural': 'Группы подразделений',
                'ordering': ('subdivisiongroupname',),
            },
        ),
        migrations.CreateModel(
            name='Workstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=100, verbose_name='Рабочий статус')),
            ],
            options={
                'verbose_name': 'Рабочий статус',
                'verbose_name_plural': 'Рабочие статусы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('subdivisionname', models.CharField(max_length=255, verbose_name='Наименование подразделения')),
                ('subdivision_short_name', models.CharField(blank=True, max_length=70, null=True, verbose_name='Сокращенное наименование подразделения')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Subdivisiongroup')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ('subdivisionname',),
            },
        ),
        migrations.CreateModel(
            name='OtherAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='Инициалы')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('academicdegree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Academicdegree', verbose_name='Ученая степень')),
                ('academicrank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Academicrank', verbose_name='Ученое звание')),
            ],
            options={
                'verbose_name': 'Сторонний автор',
                'verbose_name_plural': 'Сторонние авторы',
                'ordering': ('lastname',),
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_access', models.IntegerField(default=0)),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('dateofbirth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('positiondate', models.DateField(blank=True, null=True, verbose_name='Дата назначения на должность')),
                ('isdocentvak', models.BooleanField(default=False, verbose_name='Является доцентом ВАК')),
                ('docentvakdate', models.DateField(blank=True, null=True, verbose_name='Дата присовения доцента ВАК')),
                ('isprofessor', models.BooleanField(default=False, verbose_name='Является профессором')),
                ('professordate', models.DateField(blank=True, null=True, verbose_name='Дата присвоения профессороской степени')),
                ('iscandidate', models.BooleanField(default=False, verbose_name='Является кандидатом наук')),
                ('candidatedate', models.DateField(blank=True, null=True, verbose_name='Дата присвоения кандидата наук')),
                ('candidatetitle', models.TextField(blank=True, null=True, verbose_name='Название кандидатской диссертации')),
                ('isdoctor', models.BooleanField(default=False, verbose_name='Является доктором наук')),
                ('doctordate', models.DateField(blank=True, null=True, verbose_name='Дата присвоения доктора наук')),
                ('doctortitle', models.TextField(blank=True, null=True, verbose_name='Название докторской диссертации')),
                ('extradata', models.TextField(blank=True, null=True, verbose_name='Дополнительные данные')),
                ('candidatespecialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Candidatespecialty', verbose_name='Кандидатская специальность')),
                ('doctorspecialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Doctorspecialty', verbose_name='Докторская специальность')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Position', verbose_name='Должность')),
                ('rank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Rank', verbose_name='Звание')),
                ('subdivision', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Subdivision', verbose_name='Подразделение')),
                ('workstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.Workstatus', verbose_name='Рабочий статус')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ('lastname',),
            },
        ),
    ]
