# Generated by Django 2.2.7 on 2020-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdivision',
            name='img_path',
            field=models.TextField(blank=True, null=True, verbose_name='Путь к фото'),
        ),
    ]
