# Generated by Django 2.2.7 on 2021-02-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_subdivision_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherauthor',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
